# Generated by Django 6.1 on 2026-09-01 14:32

import django.db.models.deletion
import reviews.domain
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=32)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('code', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('summary', models.TextField()),
                ('total_score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('grade', models.CharField(max_length=8)),
                ('band', models.CharField(max_length=64)),
                ('band_meaning', models.TextField(blank=True)),
                ('marking_scheme_version', models.CharField(max_length=16)),
                ('calculation_explanation', models.TextField(blank=True)),
                ('adjustments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewEvaluationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('feedback', models.TextField(blank=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='reviews.review')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ReviewIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[(reviews.domain.IssueType['BUG'], reviews.domain.IssueType['BUG']), (reviews.domain.IssueType['SECURITY'], reviews.domain.IssueType['SECURITY']), (reviews.domain.IssueType['PERFORMANCE'], reviews.domain.IssueType['PERFORMANCE']), (reviews.domain.IssueType['CODE_QUALITY'], reviews.domain.IssueType['CODE_QUALITY']), (reviews.domain.IssueType['MAINTAINABILITY'], reviews.domain.IssueType['MAINTAINABILITY']), (reviews.domain.IssueType['BEST_PRACTICE'], reviews.domain.IssueType['BEST_PRACTICE'])], max_length=32)),
                ('severity', models.CharField(choices=[(reviews.domain.Severity['CRITICAL'], reviews.domain.Severity['CRITICAL']), (reviews.domain.Severity['HIGH'], reviews.domain.Severity['HIGH']), (reviews.domain.Severity['MEDIUM'], reviews.domain.Severity['MEDIUM']), (reviews.domain.Severity['LOW'], reviews.domain.Severity['LOW']), (reviews.domain.Severity['INFO'], reviews.domain.Severity['INFO'])], max_length=16)),
                ('confidence', models.CharField(choices=[(reviews.domain.Confidence['CONFIRMED'], reviews.domain.Confidence['CONFIRMED']), (reviews.domain.Confidence['POSSIBLE'], reviews.domain.Confidence['POSSIBLE'])], max_length=16)),
                ('line', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('suggestion', models.TextField(blank=True)),
                ('suggested_code', models.TextField(blank=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='reviews.review')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='reviews_rev_user_id_eeecea_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewevaluationcategory',
            constraint=models.UniqueConstraint(fields=('review', 'position'), name='unique_category_position_per_review'),
        ),
        migrations.AddConstraint(
            model_name='reviewissue',
            constraint=models.UniqueConstraint(fields=('review', 'position'), name='unique_issue_position_per_review'),
        ),
    ]
